"""
Django settings for axel_pay_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta 
import base64
import hashlib
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--e^fqp81il@=#ov8&4ets644h#v%wx1yw_!x-7@mh)(6&&2ea6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.230', 'localhost', '127.0.0.1']
MOBILE_MONEY_WEBHOOK_SECRET = os.environ.get("MOBILE_MONEY_WEBHOOK_SECRET")

# Clé de chiffrement applicatif AES-256-GCM du jeton STS (api/crypto.py,
# point 1 de l'audit du 24/07/2026 — remplace le stockage en clair de
# TransactionsPrepayees.token_genere).
#
# ⚠️ PRODUCTION : définir la variable d'environnement TOKEN_ENCRYPTION_KEY
# avec 32 octets aléatoires encodés en base64 standard, générés par exemple
# avec :
#   python -c "import secrets, base64; print(base64.b64encode(secrets.token_bytes(32)).decode())"
# et la fournir via un gestionnaire de secrets (jamais commitée dans le
# dépôt). Si cette variable change, tous les jetons déjà chiffrés avec
# l'ancienne clé deviennent indéchiffrables : en cas de rotation, prévoir un
# mécanisme de migration (déchiffrer avec l'ancienne clé, rechiffrer avec la
# nouvelle) plutôt qu'un simple remplacement de la variable.
#
# En dev (variable absente), on dérive une clé déterministe à partir de
# SECRET_KEY : ce n'est PAS une pratique à reproduire en production (la
# clé de chiffrement doit être indépendante de SECRET_KEY et générée
# aléatoirement), mais ça évite de casser le déchiffrement à chaque
# redémarrage du serveur de dev tant qu'aucune vraie clé n'a été configurée.
_token_encryption_key_b64 = os.environ.get("TOKEN_ENCRYPTION_KEY")
if _token_encryption_key_b64:
    TOKEN_ENCRYPTION_KEY = base64.b64decode(_token_encryption_key_b64)
else:
    TOKEN_ENCRYPTION_KEY = hashlib.sha256(SECRET_KEY.encode("utf-8")).digest()



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                          # ← à ajouter
    'rest_framework_simplejwt',                # ← à ajouter
    'rest_framework_simplejwt.token_blacklist',
    'api',
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'axel_pay_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axel_pay_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Dans axel_pay_project/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'axel',  # Remplace par le nom de ta BDD existante
        'USER': 'postgres',           # Remplace par ton utilisateur Postgres (ex: postgres)
        'PASSWORD': 'loric2007',       # Remplace par ton mot de passe Postgres
        'HOST': 'localhost',                  # Ou l'IP de ton serveur de BDD
        'PORT': '5432',                       # Port par défaut de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "api.authentication.UsersJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),   # CDC 11.1 : 15-30 min
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}




# En dev uniquement — à restreindre en prod
# `flutter run -d chrome` choisit un port aléatoire à chaque lancement :
# une liste figée (ex: "http://localhost:5000") ne matche presque jamais
# l'origine réelle, et le navigateur bloque alors le POST après un
# pré-vol OPTIONS qui semble pourtant réussir (200) côté serveur — le 200
# vient du handler OPTIONS générique de DRF, pas de CorsMiddleware, donc
# aucun en-tête Access-Control-Allow-Origin n'est ajouté à la réponse.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]