# Generated by Django 6.0.7 on 2026-07-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id_adresse', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier_description', models.TextField()),
                ('est_immeuble', models.BooleanField()),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'db_table': 'adresses',
                'db_table_comment': "Référentiel des adresses d'installation, évite la duplication sur un immeuble multi-compteurs.",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id_audit', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('objet_touche', models.CharField(max_length=150)),
                ('motif', models.TextField(blank=True, null=True)),
                ('ip_adresse', models.CharField(max_length=45)),
                ('terminal', models.CharField(blank=True, max_length=150, null=True)),
                ('date_heure', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_logs',
                'db_table_comment': "Piste d'audit de toute action administrative sensible, y compris impersonation (RG-04) \x97 APPEND-ONLY.",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComptesTechniques',
            fields=[
                ('id_compte_tech', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=100)),
                ('cle_api_hash', models.CharField(max_length=255)),
                ('scope', models.TextField()),
                ('statut', models.TextField()),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'db_table': 'comptes_techniques',
                'db_table_comment': "Comptes des intégrations automatisées (webhooks, synchronisation Eneo) \x97 jamais les droits d'un administrateur humain (RG-05).",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compteurs',
            fields=[
                ('id_compteur', models.AutoField(primary_key=True, serialize=False)),
                ('numero_compteur', models.CharField(max_length=25, unique=True)),
                ('type_compteur', models.TextField()),
                ('proprietaire_legal', models.CharField(max_length=150)),
                ('statut', models.TextField()),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'db_table': 'compteurs',
                'db_table_comment': "Compteur physique Eneo (prépayé ou postpayé), rattaché à un contrat, point d'ancrage de l'historique financier.",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id_contrat', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrat', models.CharField(max_length=30, unique=True)),
                ('statut', models.TextField()),
                ('date_creation', models.DateTimeField()),
                ('date_resiliation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrats',
                'db_table_comment': 'Racine du graphe de propriété : un utilisateur détient un ou plusieurs contrats, chacun regroupant un ou plusieurs compteurs.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturesPostpayees',
            fields=[
                ('id_facture', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('mois_facturation', models.DateField()),
                ('index_consommation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.TextField()),
                ('date_limite', models.DateField()),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'db_table': 'factures_postpayees',
                'db_table_comment': 'Historique des factures mensuelles des compteurs postpayés.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionCompteurs',
            fields=[
                ('id_delegation', models.AutoField(primary_key=True, serialize=False)),
                ('type_droit', models.TextField(db_comment='Nature du droit délégué : Lecture, Paiement ou Lecture_Paiement. Les valeurs historiques Gestionnaire/Tiers_Lecture/Tiers_Paiement restent lisibles mais ne sont plus produites.')),
                ('statut', models.TextField()),
                ('date_octroi', models.DateTimeField()),
                ('date_revocation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gestion_compteurs',
                'db_table_comment': 'REFONTE v1.5 — Délégations à des tiers (lecture et/ou paiement), portant sur un compteur précis ou sur un contrat entier. Ne modélise plus la propriété primaire.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueArchive',
            fields=[
                ('id_archive', models.AutoField(primary_key=True, serialize=False)),
                ('table_origine', models.TextField()),
                ('id_origine', models.CharField(max_length=25)),
                ('donnees_json', models.JSONField()),
                ('date_archivage', models.DateTimeField()),
            ],
            options={
                'db_table': 'historique_archive',
                'db_table_comment': 'Bascule des enregistrements de plus de 12 mois (RG-14) \x97 APPEND-ONLY, jamais de suppression.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Litiges',
            fields=[
                ('id_litige', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=2)),
                ('statut', models.TextField()),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True, null=True)),
                ('date_ouverture', models.DateTimeField()),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'litiges',
                'db_table_comment': 'Politique de gestion des litiges à trois niveaux (diagnostic, vérification comptable, résolution).',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id_notification', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('canal', models.TextField()),
                ('niveau_criticite', models.TextField()),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('statut', models.TextField()),
                ('date_envoi', models.DateTimeField()),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'db_table_comment': 'Historique des messages envoyés, orchestrés selon la matrice de criticité multicanale.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id_paiement', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('type_paiement', models.TextField()),
                ('reference_cible', models.CharField(db_comment='Référence polymorphe vers Factures_Postpayees.id_facture ou Transactions_Prepayees.id_transaction, selon type_paiement. Validée par le trigger trg_verifier_reference_cible_paiement.', max_length=25)),
                ('agregateur', models.TextField()),
                ('operateur_mobile_money', models.TextField()),
                ('numero_mobile_money', models.CharField(max_length=20)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais_agregateur_fcfa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.TextField()),
                ('numero_recu', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('donnees_recu_json', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(db_comment="Identifiant de corrélation technique inter-systèmes (§7.5), permet de reconstituer le parcours complet d'une transaction en cas de litige.", max_length=50)),
                ('date_initiation', models.DateTimeField()),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paiements',
                'db_table_comment': 'Table unifiée des règlements (facture postpayée OU recharge prépayée), référence polymorphe via reference_cible.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id_tarif', models.AutoField(primary_key=True, serialize=False)),
                ('type_compteur', models.TextField()),
                ('prix_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarifs',
                'db_table_comment': 'Grille tarifaire historisée du prix du kWh (RG-07 : le prix appliqué est figé dans chaque transaction).',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionsPrepayees',
            fields=[
                ('id_transaction', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_kwh_applique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valeur_kwh', models.DecimalField(decimal_places=3, max_digits=10)),
                ('token_genere', models.CharField(blank=True, db_comment='Jeton de recharge STS à 20 chiffres, chiffré au repos (AES-256) au niveau applicatif avant stockage.', max_length=255, null=True)),
                ('statut_paiement', models.TextField()),
                ('date_transaction', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions_prepayees',
                'db_table_comment': 'Historique des recharges de crédit prépayé \x97 APPEND-ONLY (RG-12), hors statut_paiement/token_genere.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserConsentLogs',
            fields=[
                ('id_consent', models.AutoField(primary_key=True, serialize=False)),
                ('canal', models.CharField(max_length=50)),
                ('version_cgu', models.CharField(max_length=20)),
                ('action', models.TextField()),
                ('ip_adresse', models.CharField(max_length=45)),
                ('date_consentement', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_consent_logs',
                'db_table_comment': 'Preuve opposable du consentement RGPD \x97 APPEND-ONLY.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('id_device', models.AutoField(primary_key=True, serialize=False)),
                ('fcm_token', models.CharField(max_length=255, unique=True)),
                ('type_appareil', models.TextField()),
                ('statut', models.TextField()),
                ('date_enregistrement', models.DateTimeField()),
                ('date_derniere_activite', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_devices',
                'db_table_comment': 'Terminaux et jetons FCM enregistrés pour les notifications push.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(db_comment='Empreinte du mot de passe (Argon2id) \x97 jamais stocké en clair.', max_length=255)),
                ('situation_matrimoniale', models.TextField(blank=True, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.TextField()),
                ('statut_compte', models.TextField()),
                ('tentatives_connexion_echouees', models.IntegerField()),
                ('date_verrouillage', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField()),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'Comptes utilisateurs humains (clients, gestionnaires, tiers autorisés, agents terrain, admins back-office).',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookLogs',
            fields=[
                ('id_webhook', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('id_evenement_agregateur', models.CharField(max_length=100, unique=True)),
                ('payload_brut', models.JSONField()),
                ('signature_hmac_valide', models.BooleanField()),
                ('date_reception', models.DateTimeField()),
            ],
            options={
                'db_table': 'webhook_logs',
                'db_table_comment': 'Registre brut des notifications entrantes des agrégateurs Mobile Money \x97 APPEND-ONLY (RG-09, idempotence).',
                'managed': False,
            },
        ),
    ]
