"""
Django settings for axel_pay_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta 
import base64
import hashlib
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables du fichier .env (placé à côté de manage.py) dans
# os.environ AVANT tous les os.environ.get(...) ci-dessous. Sans cet appel,
# le .env est ignoré et toutes les valeurs par défaut (souvent None) sont
# utilisées à la place.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--e^fqp81il@=#ov8&4ets644h#v%wx1yw_!x-7@mh)(6&&2ea6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
GEMINI_API_KEY= os.environ.get("GEMINI_API_KEY","AQ.Ab8RN6KNdxUjbCjjE_hXSrgp5yihCZxmr34VCKjT-abOkljbkw")
ALLOWED_HOSTS = ['192.168.1.230', 'localhost', '127.0.0.1']
MOBILE_MONEY_WEBHOOK_SECRET = os.environ.get("MOBILE_MONEY_WEBHOOK_SECRET")

# ==============================================================================
# NOTCHPAY — Agrégateur Mobile Money (module 5 — api/services/notchpay.py)
# ==============================================================================
# Clés de l'espace SANDBOX NotchPay (préfixe pk_test./sk_test./hsk_test.).
# Elles sont lues depuis l'environnement en priorité ; la valeur en dur
# ci-dessous n'est qu'un secours pour ne pas casser l'environnement de dev
# tant qu'aucune variable n'est positionnée — exactement le même principe
# que TOKEN_ENCRYPTION_KEY plus haut. Le jour où vous basculez sur des clés
# pk_live/sk_live, définissez les variables d'environnement correspondantes
# ET repassez NOTCHPAY_SANDBOX_FORCER_MONTANT_ZERO à False (voir plus bas) :
# ne JAMAIS déployer ce fichier tel quel en production avec des clés live.
NOTCHPAY_PUBLIC_KEY = os.environ.get(
    "NOTCHPAY_PUBLIC_KEY",
    "pk_test.YAdNJkDataeoPbYE07cl88AY4zczo0Cal1U8KvAEH0FXSsIyMCJyzloa2lHbNlDmyK5tYsIAKW5c4SRs8LnjkAPk1xKs2nOTixNQggEVsK1WiLgNjUJb8bvBXQvcv",
)
NOTCHPAY_PRIVATE_KEY = os.environ.get(
    "NOTCHPAY_PRIVATE_KEY",
    "sk_test.X95cWc0WqJFblt0uWkFTCzB19jh4epVpZviOApWzUEedreDRGyUsMTHxf8Rq2wXGEC8DQqxSp7T8CkeCVWlTl2tRytk7JOfEExnUTXlixlDYgeWNqMgvIwoUoGF8k",
)
# Clé de hachage NotchPay ("Hash Key") : sert à vérifier la signature
# HMAC-SHA256 (en-tête `x-notchpay-signature`) des webhooks entrants, pour
# s'assurer qu'une notification de paiement provient bien de NotchPay et non
# d'un tiers qui en imiterait la forme (CDC 9.2, RG-08/RG-09).
NOTCHPAY_HASH_KEY = os.environ.get(
    "NOTCHPAY_HASH_KEY",
    "hsk_test.VuOO9EKk5l89CYaQ9K07SPcBFSIpxiFkT5cdUO4pgiZ7nlhF9oCKfpeZ4XaBamqdN52iB9ZtBcHhTKIY0iKbgEEmIfmOKVfsGSmCF0QGRe0bn359SP4yQCjzNuAnD",
)
NOTCHPAY_BASE_URL = os.environ.get("NOTCHPAY_BASE_URL", "https://api.notchpay.co")

# URL de terminaison (callback/webhook) exposée à NotchPay. En dev, elle
# transite par le tunnel ngrok (celui-ci change d'adresse à chaque relance
# de `ngrok http`, sauf domaine réservé) — pensez à la mettre à jour dans
# votre .env local si l'URL ngrok change, plutôt que de modifier ce fichier.
NOTCHPAY_CALLBACK_URL = os.environ.get(
    "NOTCHPAY_CALLBACK_URL",
    "https://munchkin-native-distant.ngrok-free.app/api/webhooks/notchpay/",
)

# ⚠️ MODE SANDBOX DE TEST — cf. api/services/notchpay.py::initialiser_paiement.
# Quand ce flag est actif, le montant RÉELLEMENT envoyé à l'API NotchPay est
# systématiquement forcé à 0 FCFA, quel que soit le montant métier saisi par
# l'utilisateur (500, 12 000, ...). Cela permet de dérouler tout le parcours
# (push USSD, webhook, génération de jeton) en sandbox sans dépendre d'un
# solde de test suffisant chez l'opérateur Mobile Money. Le montant métier
# réel reste, lui, celui enregistré dans `Paiements.montant_fcfa` — seule la
# valeur transmise à l'agrégateur est modifiée.
# Par défaut : actif seulement si des clés `_test.` sont détectées, pour
# qu'un déploiement avec des clés live désactive automatiquement le
# comportement même en cas d'oubli. Vous pouvez aussi le piloter
# explicitement via la variable d'environnement NOTCHPAY_SANDBOX_ZERO_FCFA.
NOTCHPAY_SANDBOX_FORCER_MONTANT_ZERO = os.environ.get(
    "NOTCHPAY_SANDBOX_ZERO_FCFA",
    "true" if "_test." in NOTCHPAY_PUBLIC_KEY else "false",
).lower() in ("1", "true", "yes")


# ==============================================================================
# ORANGE SMS API — envoi des OTP et notifications critiques par SMS (CDC 10)
# ==============================================================================
# `ORANGE_SMS_CLIENT_ID` peut avoir une valeur de secours en dev (ce n'est
# pas un secret à proprement parler côté OAuth2 client_credentials, mais on
# évite tout de même de le committer en dur sur le long terme). En revanche
# `ORANGE_SMS_CLIENT_SECRET` n'a AUCUNE valeur de secours : sans variable
# d'environnement positionnée, l'envoi de SMS échoue explicitement plutôt que
# de tenter un appel avec un secret manquant ou deviné.
ORANGE_SMS_CLIENT_ID = os.environ.get("ORANGE_SMS_CLIENT_ID", "oAfa3Cx5eMLLshSnMeR0CqFqFQFxqa3D")
ORANGE_SMS_CLIENT_SECRET = os.environ.get("ORANGE_SMS_CLIENT_SECRET")
# Numéro expéditeur (senderAddress) exigé par l'API Orange SMS, format
# `tel:+237XXXXXXXXX` — à renseigner via l'environnement selon le contrat
# Orange souscrit (aucune valeur fictive fournie ici : un mauvais expéditeur
# ferait échouer silencieusement l'envoi côté opérateur).
ORANGE_SMS_SENDER_ADDRESS = os.environ.get("ORANGE_SMS_SENDER_ADDRESS")


# ==============================================================================
# FIREBASE — Notifications push (FCM, module 6 — api/services/firebase.py)
# ==============================================================================
# Rappel d'architecture (cf. demande initiale) : Firebase sert UNIQUEMENT au
# transport des notifications push (FCM). L'authentification reste 100%
# Django/JWT (UsersJWTAuthentication) — Firebase Authentication n'est utilisé
# nulle part.
#
# `FIREBASE_CREDENTIALS_PATH` pointe vers le fichier JSON de compte de
# service (Console Firebase > Project Settings > Service accounts >
# "Generate new private key"). Contrairement à NOTCHPAY_*/ORANGE_SMS_*, ce
# n'est PAS une valeur qu'on peut committer avec un fallback en dur : c'est
# un chemin de fichier, pas un secret texte, donc il n'y a rien de sensé à
# mettre "en dur" ici — le fallback ci-dessous suppose juste que le fichier
# existe à cet emplacement local, à toi de l'y déposer (voir SETUP.md).
#
# ⚠️ Ne JAMAIS committer secrets/firebase-service-account.json — ajoute-le à
# .gitignore. En production, monte ce fichier via ton gestionnaire de
# secrets plutôt que de le déposer sur le filesystem de l'image/serveur.
FIREBASE_CREDENTIALS_PATH = os.environ.get(
    "FIREBASE_CREDENTIALS_PATH",
    BASE_DIR / "secrets" / "firebase-service-account.json",
)

# Nom du canal de notification Android par défaut (doit correspondre EXACTEMENT
# à la valeur `channel_id` utilisée côté Django dans
# api/services/firebase.py::send_push_notification ET au meta-data
# `com.google.firebase.messaging.default_notification_channel_id` dans
# android/app/src/main/AndroidManifest.xml côté Flutter).
FIREBASE_ANDROID_NOTIFICATION_CHANNEL_ID = os.environ.get(
    "FIREBASE_ANDROID_NOTIFICATION_CHANNEL_ID", "axelpay_notifications"
)


# ==============================================================================
# SMTP — envoi des e-mails (mot de passe oublié, reçus, notifications
# "Informatif", CDC 10). Aucune valeur de secours : sans configuration, on
# retombe sur la console (utile en dev, jamais en prod) plutôt que d'échouer
# silencieusement ou de deviner un serveur SMTP.
# ==============================================================================
if os.environ.get("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
else:
    # Aucune variable EMAIL_HOST définie : les e-mails sont simplement
    # affichés dans la console du serveur de dev plutôt qu'envoyés — à
    # remplacer par les identifiants SMTP réels via l'environnement.
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Clé de chiffrement applicatif AES-256-GCM du jeton STS (api/crypto.py,
# point 1 de l'audit du 24/07/2026 — remplace le stockage en clair de
# TransactionsPrepayees.token_genere).
#
# ⚠️ PRODUCTION : définir la variable d'environnement TOKEN_ENCRYPTION_KEY
# avec 32 octets aléatoires encodés en base64 standard, générés par exemple
# avec :
#   python -c "import secrets, base64; print(base64.b64encode(secrets.token_bytes(32)).decode())"
# et la fournir via un gestionnaire de secrets (jamais commitée dans le
# dépôt). Si cette variable change, tous les jetons déjà chiffrés avec
# l'ancienne clé deviennent indéchiffrables : en cas de rotation, prévoir un
# mécanisme de migration (déchiffrer avec l'ancienne clé, rechiffrer avec la
# nouvelle) plutôt qu'un simple remplacement de la variable.
#
# En dev (variable absente), on dérive une clé déterministe à partir de
# SECRET_KEY : ce n'est PAS une pratique à reproduire en production (la
# clé de chiffrement doit être indépendante de SECRET_KEY et générée
# aléatoirement), mais ça évite de casser le déchiffrement à chaque
# redémarrage du serveur de dev tant qu'aucune vraie clé n'a été configurée.
_token_encryption_key_b64 = os.environ.get("TOKEN_ENCRYPTION_KEY")
if _token_encryption_key_b64:
    TOKEN_ENCRYPTION_KEY = base64.b64decode(_token_encryption_key_b64)
else:
    TOKEN_ENCRYPTION_KEY = hashlib.sha256(SECRET_KEY.encode("utf-8")).digest()



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                          # ← à ajouter
    'rest_framework_simplejwt',                # ← à ajouter
    'rest_framework_simplejwt.token_blacklist',
    'api',
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'axel_pay_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axel_pay_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Dans axel_pay_project/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'axel',  # Remplace par le nom de ta BDD existante
        'USER': 'postgres',           # Remplace par ton utilisateur Postgres (ex: postgres)
        'PASSWORD': 'loric2007',       # Remplace par ton mot de passe Postgres
        'HOST': 'localhost',                  # Ou l'IP de ton serveur de BDD
        'PORT': '5432',                       # Port par défaut de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "api.authentication.UsersJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),   # CDC 11.1 : 15-30 min
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}




# En dev uniquement — à restreindre en prod
# `flutter run -d chrome` choisit un port aléatoire à chaque lancement :
# une liste figée (ex: "http://localhost:5000") ne matche presque jamais
# l'origine réelle, et le navigateur bloque alors le POST après un
# pré-vol OPTIONS qui semble pourtant réussir (200) côté serveur — le 200
# vient du handler OPTIONS générique de DRF, pas de CorsMiddleware, donc
# aucun en-tête Access-Control-Allow-Origin n'est ajouté à la réponse.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]